### PR TITLE
Fix for ScopeWideningException

### PR DESCRIPTION
**Pull request by creatiombe**
I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}

## Changelog

```markdown
### Added
- Added some `Class::newMethod` to do great stuff

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

## To do

- [ ] Update the tests
- [ ] Update the documentation
- [ ] Add an upgrade note

### CODE REVIEW

**Comment by jordisala1991** [comment]
Are you using Symfony 2.3?

**Comment by creatiombe** [comment]
No im using Symfony 2.8, i attached my composer.json, remove my repo to see the error:


[composer.zip](https://github.com/a2lix/TranslationFormBundle/files/1806117/composer.zip)

**Comment by creatiombe** [comment]
It might be that request is not used anymore and you need to replace it by request_stack, i didnt test this completely yet.

**Comment by jordisala1991** [comment]
Yes, we should move to request_stack indeed

**Comment by jordisala1991** [comment]
If you have time to do it in a BC way, go for it.

Otherwise I will do it tonight.

**Pull request closed without merging**
