### PR TITLE
Symfony 4 support

### PR DESCRIPTION
**Pull request by Bukashk0zzz**

### CODE REVIEW

**Comment by webda2l** [comment]
Please use right JSON format (see https://jsonlint.com/) and keep the EOL

**Comment by jordisala1991** [comment]
it would be nice if we can have this compatibility on the 2.x branch

**Comment by bocharsky-bw** [comment]
Hey @Bukashk0zzz, can you revert unnecessary indentation so we can go further with it?

**Comment by jordisala1991** [comment]
probably it would be better if you redo this PR from scratch, because @Bukashk0zzz removed his fork

**Comment by Bukashk0zzz** [comment]
Hi, give me few minutes. I will fix this PR.

**Comment by Bukashk0zzz** [comment]
Created new one https://github.com/a2lix/TranslationFormBundle/pull/286
And fixed json problems.

**Pull request closed without merging**
