### PR TITLE
compatibility with easycorp/easyadmin-bundle v3.4.2 and so bootstrap5

### PR DESCRIPTION
**Pull request by justin-petermann**
I am targeting this branch, because it's logics...

Closes none issue... i had a problem a contribute... you can change after if you wants, but in new version

the tabs didn't work anymore with new version of easyadmin from 3 days ago

## Changelog

add file src/Resources/views/bootstrap_5_layout.html.twig

```markdown
### Added
add file src/Resources/views/bootstrap_5_layout.html.twig

### Changed

nothing else

### Deprecated

### Removed

### Fixed

### Security
```

## To do

- [ ] Update the tests
- [ ] Update the documentation
- [ ] Add an upgrade note

### CODE REVIEW

**Comment by Ishadijcks** [comment]
I have the same problem, but using this layout doesn't fix it.

Did you manage to find a workaround @justin-petermann?

**Comment by jmeyo** [comment]
You have to add this form theme through the easyadmin method.

While waiting for this form theme to be merged you can add it in your templates directory and then configure it through the congiurueCrud method.

If you want to add it globally, add this in your dashboard (considering you added this form theme in ```templates/admin/a2lix_bootstrap_5_layout.html.twig```):
```
    public function configureCrud(): Crud
    {
        return Crud::new()
            ->addFormTheme('admin/a2lix_bootstrap_5_layout.html.twig')

            // other global crud settings
            ->setDefaultSort(['id' => 'DESC'])
            ->setPaginatorPageSize(15)
;
    }
```

**Review by enekochan — APPROVED** [review]
Works as spected in EasyAdmin 3.

**Comment by tchapi** [comment]
This is a duplicate of https://github.com/a2lix/TranslationFormBundle/pull/360 that has just been merged :)

**Pull request closed without merging**
