### PR TITLE
Symfony 4 support

### PR DESCRIPTION
**Pull request by Bukashk0zzz**

### CODE REVIEW

**Comment by jordisala1991** [comment]
Can you add support for Sf 4 on 2.x branch?

**Comment by Bukashk0zzz** [comment]
https://github.com/a2lix/TranslationFormBundle/pull/287

**Comment by welcoMattic** [comment]
Is any sf4 compatible version is planned soon? 3.x or 2.x

**Comment by jordisala1991** [comment]
Solved on #293

**Pull request closed without merging**
