### PR TITLE
Create bootstrap_5_layout.html.twig

### PR DESCRIPTION
**Pull request by cedriclombardot**
### Added

- Compatibility with bootstrap5

### CODE REVIEW

**Comment by enekochan** [comment]
Hi. This works fine. Can it be merged?

**Comment by tchapi** [comment]
Hi, 

It would be great if this could be merged, it works fine and fixes the tabs not working in Symfony5 / EA 3 !

**Review by tchapi — APPROVED** [review]

**Review by tchapi — APPROVED** [review]

**Comment by webda2l** [comment]
Thanks!

**Comment by enekochan** [comment]
@webda2l are you going to create a new release with this change or should I use master in my composer? Thank you!

**Pull request merged**
