### PR TITLE
Fix show tab with error + html5

### PR DESCRIPTION
**Pull request by ruscon**
"a2lix/translation-form-bundle": "2.1.2"

### CODE REVIEW

**Comment by ruscon** [comment]
ping ?

**Comment by ruscon** [comment]
ping ?

**Comment by jordisala1991** [comment]
What are you trying to fix with this change?
Can you rebase on 2.x?

**Comment by webda2l** [comment]
There is no more JS file with latest version of this bundle.
The tab functionality rely on Twitter bootstap JS files.

**Pull request closed without merging**
