### PR TITLE
Symfony composer

### LINKED ISSUE #111: Dependency on symfony/symfony
I use symfony/form with different framework than symfony and I'd like to use this as well. However the fact that this package requires the whole symfony/symfony package instead of just some of its components prevents me from doing so.

Can you update your composer.json to require just the necessary symfony components and maybe suggest some others?

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #111.

I also added a `.gitignore` file for composer.

### CODE REVIEW

**Comment by enumag** [comment]
Can you simplify the dependencies to just symfony/form? This is still useless for me. I use symfony/form in my application but I don't have symfony/config, symfony/dependency-injection or symfony/http-kernel installed. And I don't think I'll actually need them for this bundle either.

**Comment by Soullivaneuh** [comment]
@enumag I don't think so. This is delivered as a bundle and a bundle need those dependencies.

**Comment by enumag** [comment]
@Soullivaneuh It does not. You need to tell the difference between real dependencies and optional dependencies. Sure some classes won't work without the optional dependencies but it will still be possible to use the core of the package. In this case only symfony/form is actually needed.

**Comment by Soullivaneuh** [comment]
@enumag Maybe can you elaborate your concrete case?

For the moment I will let this as is because I still think this project is aim to be shipped as a bundle and nothing else.

In any case, I let @webda2l make the final decision and will update the PR accordingly.

**Comment by enumag** [comment]
The core of this package are pretty much [these files](https://github.com/a2lix/TranslationFormBundle/tree/master/Form/Type) excluding TranslatedEntityType.php. When you look into them you can see that the only real dependencies are symfony/form and symfony/options-resolver.

Also you might find it helpful to look at this from the other side. Why didn't you add twig/twig to the dependencies? The [views](https://github.com/a2lix/TranslationFormBundle/tree/master/Resources/views) won't work without it right? I believe you know the answer to that one - the same answer applies for symfony/config, symfony/dependency-injection and symfony/http-kernel.

**Comment by Soullivaneuh** [comment]
> Why didn't you add twig/twig to the dependencies?

Simply because is not using twig classes. :-)

**Comment by enumag** [comment]
@Soullivaneuh What about Gedmo then? https://github.com/a2lix/TranslationFormBundle/blob/master/Util/Gedmo/GedmoTranslatable.php

**Comment by Soullivaneuh** [comment]
This is not the same IMHO.

Gedmo is an optional dep because this bundle aim to handle multiple translation management libraries.

**Comment by enumag** [comment]
Then why exactly it should not aim to be usable with different frameworks than symfony?

**Comment by Soullivaneuh** [comment]
I understand your point of view. But I don't think this is the point of view of the maintener.

If yes, the structure and name should not be the same IMO, as I did for this project : https://github.com/Soullivaneuh/IsoCodesValidator

Let's see maintainer decision.

**Comment by webda2l** [comment]
Thanks for contribute, 3.x branch do things better. I let the 2.x as current.

**Comment by Soullivaneuh** [comment]
Can I ask why doing this stuff on a new major release? Those changes are completely BC and can be made on a patch or a minor version IMHO.

**Comment by Soullivaneuh** [comment]
ping @webda2l

**Pull request closed without merging**
