### PR TITLE
:bug: Fix form validation when locale is required (knp behaviors)

### LINKED ISSUE #356: validation not workings on entity translation
Hi, 
I'm trying to manage translations about a "Page" entity.
I have NotBlank constraint on "title" field in the "PageTranslation" entity but its not working... When I submit the form with empty values, it's valid... 
If you have an idea about where is the problem... you're welcome !
I'm using SF 4.4

Here is the code

### Page.php

```
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 * @ORM\Table(name="page")
 */
class Page implements TranslatableInterface
{
    use Common\IdTrait;
    use TranslatableTrait;
    use TimestampableEntity;

    /**
     * @Assert\Valid()
     */
    protected $translations;

    public function __call($method, $arguments)
    {
        return PropertyAccess::createPropertyAccessor()->getValue($this->translate(), $method);
    }

}
```

### PageTranslation.php

```
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslationTrait;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="page_translations")
 */
class PageTranslation implements TranslationInterface
{
    use Common\IdTrait;
    use Common\SeoTrait;
    use TranslationTrait;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", nullable=true, length=150)
     * @Assert\NotBlank()
     */
    protected $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    protected $description;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return PageTranslation
     */
    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return PageTranslation
     */
    public function setDescription($description)
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     * @return PageTranslation
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
        return $this;
    }
}
```

### PageType.php
```
<?php

namespace App\Form;

use A2lix\TranslationFormBundle\Form\Type\TranslationsType;
use App\Entity\Page;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PageType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {

        $builder
            ->setMethod('POST')
            ->add('save', SubmitType::class, array(
                'label' => 'Valider',
            ))
        ;
        
        $builder
            ->add('translations', TranslationsType::class, [
            'fields' => [
                'title' => [
                    'field_type' => TextType::class,
                    'locale_options' => [
                        'en' => [
                            'attr' => ['class' => 'form-control-lg form-control-solid'],
                        ],     
                        'fr' => [
                            'attr' => ['class' => 'form-control-lg form-control-solid'],
                        ],     
                    ]
                ],
            ],
            'excluded_fields' => ['description', 'slug']            // [2]
        ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Page::class,
            'validation_groups' => function (FormInterface $form) {
                return ['Default'];
            },
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'page_form';
    }
}
```

### PageController.php
```
.................
/**
     * @Route("/page/add", name="page_add")
     * @Template("page/add.html.twig")
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return array|Response
     */
    public function add(Request $request, EntityManagerInterface $em)
    {

        $page = new Page();

        $form = $this->createForm(PageType::class, $page, [
            'attr' => [
                'novalidate' => 'novalidate'
            ]
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            if ($form->isValid()) {

                $em->persist($page);
                $em->flush();

                ..................................

            } else {

                .................
            }

        }

        return [
            'page'      => $page,
            'form'      => $form->createView()
        ];
    }
....................
```

### a2lix.yaml
```
a2lix_translation_form:
  locale_provider: default       
  locales: [fr,en]      
  default_locale: 'fr'             
  required_locales: [fr,en]         
  templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"      
```

### LINKED ISSUE #361: Required languages not validated
Hello!

I am using a2lix translation form (3.0.7) with doctrine behavior (2.2.0). I managed to get the translated entities validated (using validation in yaml file) but this only works when at least one field in each language is populated. If for example you have 2 required languages and you add informations for one and leave all fields for second mandatory language empty, this will not generate a validation error. Any idea on how to fix that?
Thx!

### PR DESCRIPTION
**Pull request by grizzlylab**
I am targeting master because a tag 3.0.11 will be probably needed. And to be honest Iam not sure which branch to target, maybe the version 2 is relevant (but automatic merge was not possible). Let me know how I can help. I think the subject of this PR is very important and Iam ready to follow rules and modify it in order to see it merged. Thank you for your time.

Closes #361
Closes #356

```markdown
## Changelog

Fix form validation for required locales.

### Fixed

Form validation for required locales.

## To do

Check if this fix is only relevant when using knp behaviors or if it can be applied globally.

## Subject

A check is added for required locale when submiting the form, the element is not removed if the locale is required in order to trigger the "NotBlank" constraint. Otherwise, there is no validation (can submit all fields being empty).
```

### CODE REVIEW

**Comment by grizzlylab** [comment]
To reproduce the issue, it is needed to work with collection.

Where en is a required locale

Before fix

Possible to edit  1 item by clearing **all fields** and then save the item, it will then remove all translations, even the translation being required (here en). 
 
After fix : 

Form validation triggered about en field for items not having a string, as the element for en is not removed (behavior in the fix), validation is applied on it ("This value should not be blank.")

Screenshot from 2022-01-11 16-34-44

**Comment by tchapi** [comment]
hi @grizzlylab and thanks a lot for this PR

I will try to review it asap.
Could you just remove the modifications in `composer.json` ? I don't think they're related and it's better if we keep the commit history clean and tidy (but I may be wrong)

**Comment by grizzlylab** [comment]
@tchapi I removed the composer.json modifications.

**Comment by tchapi** [comment]
Sorry I'm being overwhelmed with many other things to do at work and haven't had the chance to look yet at the PR. Still in my priority list though!

**Review by tchapi — APPROVED** [review]

**Comment by webda2l** [comment]
Hi,
Ok to me. With or without your code @tchapi, as you want!
(I think very few people use this bundle with a provider different than KNP)

**Review by webda2l — APPROVED** [review]

**Comment by grizzlylab** [comment]
@tchapi @webda2l Thank you !

**Comment by grizzlylab** [comment]
Hello @tchapi, can we release a tag for this ?

**Comment by webda2l** [comment]
Hello @grizzlylab,
Done https://github.com/a2lix/TranslationFormBundle/tree/3.2.1
Thanks

**Pull request merged**
